version: "3.3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin}
      - MONGO_DATABASE=${MONGO_DATABASE:-videoclub}
      - PRODUCTION=${PRODUCTION:-true}

  processor:
    user: node:node
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - TZ=UTC
      - MONGO_USER=${MONGO_USER:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-admin}
      - MONGO_DATABASE=${MONGO_DATABASE:-videoclub}
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - NODE_ENV=${PRODUCTION:-false}
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
